apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    name: gateway-service
    app: microservice
spec:
  type: LoadBalancer
  ports:
    - port: http  80/TCP
      targetPort: 80/TCP
      nodePort: http  30010/TCP
  selector:
     app: gateway
     type: microservice