apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: microservice-libreria
    name: mongo-pod
spec:
  containers:
    - name: mongo
      image: mongo:latest
      command:
        - /bin/bash
        - -c
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "jfpljfpl"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "JfplJfpl2025"